CREATE DATABASE IF NOT EXISTS WalletTrake;
USE WalletTrake;
CREATE TABLE IF NOT EXISTS users(
CIN VARCHAR(50) NOT NULL PRIMARY KEY,
name VARCHAR(30) NOT NULL ,
email VARCHAR(100) NOT NULL UNIQUE,
password_hash VARCHAR(255) NOT NULL,
register_at DATETIME DEFAULT CURRENT_TIMESTAMP,
);